name: cicdTest


on:
  push:
    branches: 
            - master
jobs:
 my_testing:
    runs-on: ubuntu-latest

    steps:    
      - name: Run Test
        run : echo "Hello, Test"
        
        
 my_deploy:
   runs-on: ubuntu-latest
   
   steps:
     - name: Run Deploy
       run : echo "Hello, Deploy"
